# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 임용태
title: Backend Engineer
email: lyt032410@gmail.com
website: https://jessyt.tistory.com/

# Dark Mode (true/false/never)
#darkmode: false

# Social links
#twitter_username: facespics
github_username:  yongtaelim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs

  안녕하세요. 백엔드 개발자입니다. <br>
  Java, Kotlin 언어를 사용한 Spring Boot 프레임워크 기반으로 개발을 진행해왔습니다. <br>
  2번의 스타트업으로 서비스 아키텍트부터 개발, 운영까지 경험하였습니다. <br>

  현재는 이커머스 서비스의 전반적인 기능, 관리자, 배치를 담당하고 있습니다.
  서비스를 탄탄하게 운영하는 포인트에 집중을 많이 하는 편입니다. 단편적인 예로 모니터링과 테스트 코드에 대해 매우 중요하게 생각하고 있습니다.

  협업에 대해서 매우 중요하게 생각하고 있습니다.
  개인보단 팀 단위로 생각하고 학습한 내용을 공유하며 <mark>함께 성장하는 분위기</mark>를 만드려고 노력하고 있습니다. 스터디를 진행 중이며 블로그를 작성하여 기술에 대해 공유하고 있습니다.

  모든 사람에게서는 배울 점이 있다고 생각합니다.
  연차, 나이, 직군, 파트 모두 떠나서 배울 점이 있다고 생각합니다. <mark>늘 겸손하자</mark>가 저의 가치관입니다.

content:
  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
#        link: boringcompany.com
        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Java, [Kotlin](https://jessyt.tistory.com/category/Study/kotlin)
            - Spring Boot, Spring MVC, [Spring Batch](https://jessyt.tistory.com/category/Develop/spring-batch), Spring Security, [Spring Data](https://jessyt.tistory.com/category/Develop/spring-data)
            - JPA, Querydsl
            - Junit5, Mockito
            - Gradle, Maven
            - IntelliJ
      - layout: left
        title: DevOps
        description: | # this will include new lines to allow paragraphs
            - MySQL, MariaDB, MongoDB, Redis
            - Jenkins
            - [Kafka](https://jessyt.tistory.com/category/Study/message-queue)
            - [Promethous, Grafana](https://jessyt.tistory.com/category/Develop/devops)
            - Docker
      - layout: left
        title: Etc
        description: | # this will include new lines to allow paragraphs
            - Confluence, Jira, RedMine, Yona
            - Slack

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FastView
        caption: 2021.03 - 재직중
        sub_title: 코틀린 백엔드 개발자
        quote: >
          공급사 이커머스 구성 및 운영 서비스
        description: | # this will include new lines to allow paragraphs
          Rest API 개발
          - Service: 회원 인증 / 상품 / 내정보
          - Admin: 주문 관리 / 회사 관리 / 공급사 관리
          Spring Batch 기반의 적립금/주문 상태 처리 서비스 구축
          - Kafka를 이용한 MSA 기반 배치 설계
          - Jenkins를 이용한 배포, Scheduler 생성
          TDD 기반으로 개발 진행
          2021년 2분기 MVP 수상

      - layout: left
        title: Newploy
        link: https://www.newploy.net/
        link_text: https://www.newploy.net/
        caption: 2020.07 - 2021.03
        sub_title: 개발자
        quote: >
          급여 업무 자동화 플랫폼
        description: | # this will include new lines to allow paragraphs
          Rest API 개발
          - 사업장 관리 / 사업장 등록 프로세스 / 임직원 관리
          Spring Batch 기반 급여 출금/입금 처리 서비스 구축
          - 입출금 서비스와 외부 연동 진행
          - Jenkins를 이용한 배포, Scheduler 생성
          Monitoring 구축 및 운영
          - Prometheous, Grafana 구축
          - 입금/출금 상태 Monitoring
          TDD 기반으로 개발 진행

      - layout: left
        title: Ibizsoftware
        caption: 2017.04 - 2020.07
        sub_title: 개발자
        quote: >
          BlockChain Platform && SI
        description: | # this will include new lines to allow paragraphs
          BlockChain Platform
          - [hyperledger-fabric DAPP 개발](https://github.com/yongtaelim/hyperledger-fabric-project)
            - Fabric SDK 를 사용하여 BlockChain Install 프로세스 구현
          - hyperledger-fabric에 softhsm 적용
            - softhsm을 분석하여 노드에 환경 구축
            - hyperledger-fabric에 softhsm 적용
            - [서버 구성 자동화 환경 구축](https://github.com/yongtaelim/hyperledger-fabric-hsm)
          SI
          - Spring Framework, Mysql, Oracle 환경에서의 개발

  - title: ETC
    layout: text
    content: | # this will include new lines to allow paragraphs
      꾸준하게 블로그 작성을 하여 기술 향상 및 기술 공유에 힘쓰고 있습니다.
      - [에디블로그](https://jessyt.tistory.com/)

      기존의 것을 그대로 사용하지 않고 분석하고 개선하려 힘쓰고 있습니다. 아래 내용은 블로그에 작성한 컨텐츠입니다.
      - [Querydsl 복잡한 쿼리 Paging 처리 Support Class](https://jessyt.tistory.com/129)
      - [Spring Batch QuerydslPagingItemReader 개선](https://jessyt.tistory.com/128)
      - [JPA DirtyChecking Kotlin 스럽게 사용하기](https://jessyt.tistory.com/106)
      - [Querydsl Join Query Sort 구현해보기](https://jessyt.tistory.com/90)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
